# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
