# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_choice_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='HEHE', max_length=100),
            preserve_default=False,
        ),
    ]
